%define	base_version 2.4
Summary:	Common ODB runtime library from Code Synthesis
Name:		libodb
Version:	%{base_version}.0
Release:	1
License:	GPL v2
Group:		Libraries
Source0:	http://www.codesynthesis.com/download/odb/%{base_version}/%{name}-%{version}.tar.bz2
# Source0-md5:	ae3842876f4f30c78e9d71fcf945ff7a
URL:		http://www.codesynthesis.com/products/odb/
BuildRequires:	libstdc++-devel
BuildRequires:	pkgconfig
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
ODB is an object-relational mapping (ORM) system for C++. It provides
tools, APIs, and library support that allow you to persist C++ objects
to a relational database (RDBMS) without having to deal with tables,
columns, or SQL and without manually writing any of the mapping code.

This package contains the common ODB runtime library. Every
application that includes code generated by the ODB compiler will need
to link to this library.

%package devel
Summary:	Development files for %{name}
Group:		Development/Libraries
Requires:	%{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains libraries and header files for
developing applications that use %{name}.

%prep
%setup -q

%build
%configure \
	--disable-static
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT

%{__rm} $RPM_BUILD_ROOT%{_libdir}/libodb.la
%{__rm} -r $RPM_BUILD_ROOT%{_docdir}/%{name}

%clean
rm -rf $RPM_BUILD_ROOT

%post	-p /sbin/ldconfig
%postun	-p /sbin/ldconfig

%files
%defattr(644,root,root,755)
%attr(755,root,root) %{_libdir}/libodb-%{base_version}.so

%files devel
%defattr(644,root,root,755)
%doc NEWS
%{_includedir}/odb
%{_libdir}/libodb.so
%{_pkgconfigdir}/libodb.pc
